declare:
  - name: package
    type: identifier

  - name: version
    type: version-number
    deduce: true

  - name: recipe
    type: identifier

  - name: configure-flags
    type: string-list

  - name: set-cflags-ldflags
    type: boolean

include:
  - file: sources

rules:
  # These are defaults, anything matching a when-clause will override them
  set-cflags-ldflags: yes
  recipe: configure-make-install
  configure: [--with-prefix=\$ARTIFACT]

  when package=hdf5:
    build-deps:
      - package: zlib
        version: 0 to 1.3

      - when use-szip=true:
        - package: szip

    append configure: [--with-szlib, --with-pic]

  when package=zlib:
    append configure: [--with-szlib]
    when machine=abel:
      append configure: [--with-intel=/opt/intel]
